config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  root 'sessions#new'
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  post 'checkmark' => 'tasks#checkmark'
  post 'logout' => 'sessions#destroy'

  resources :announcements
  resources :tasks
end

app/models/announcement.rb
class Announcement < ApplicationRecord
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord


  def self.clear_tasks
    Task.delete_all
  end

end

app/models/user.rb
class User < ApplicationRecord
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  def index
  end

  def create
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper

  append_before_action :require_login

  private

  def require_login
    unless current_user
      flash[:danger] = 'Please log in to access this page.'
      redirect_to root_path
    end
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :require_login

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)

    if user&.active
      login user
      redirect_to announcements_path
    else
      flash[:danger] = 'Please enter a valid email address!'
      redirect_to login_path
    end
  end

  def destroy
    logout
    redirect_to login_path
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @filter = params[:category]
    @all_categories = %w[Inventory Register Engineering]
    @tasks = if @filter.blank?
               Task.all
             else
               Task.where(category: @filter)
             end
    incomplete_task = @tasks.where(completed: false).order(priority: :desc, added: :asc)
    completed_tasks = @tasks.where(completed: true).order(:complete_time).reverse
    @tasks = incomplete_task + completed_tasks
    @num_incomplete = incomplete_task.count
    @count = 0
    @completed = false
    @curr_categories = @all_categories
    @users = User.all
  end

  def destroy
    begin
      task = Task.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to tasks_path
      flash[:danger] = 'Task no longer exists.'
    else
      Task.delete(task)
      redirect_to tasks_path(category: params[:category])
    end
  end

  def checkmark
    begin
      task = Task.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      redirect_to tasks_path
      flash[:danger] = 'Task no longer exists.'
    else
      user = User.find(params[:user])
      if params[:check_type] == 'checking' && task.completed
        redirect_to tasks_path
        flash[:danger] = "This task has already been completed by #{task.user_complete}."
      elsif params[:check_type] == 'unchecking' && !task.completed
        redirect_to tasks_path
        flash[:danger] = "This task has already been marked as incomplete by #{task.user_complete}."
      else
        task.completed = !task.completed
        task.user_complete = user.name
        task.complete_time = Time.current
        task.save!
        redirect_to tasks_path(category: params[:category])
      end
    end
  end

  def new
  end

  def create
    new_task = Task.new
    new_task.name = params[:task_name]
    new_task.description = params[:task_description]
    new_task.category = params[:task_category]
    new_task.priority = params[:priority]
    new_task.added = Time.current
    new_task.user_add = current_user.name
    new_task.completed = false
    new_task.save!
    if params[:task_category] == params[:category]
      redirect_to tasks_path(category: params[:category])
    else
      redirect_to tasks_path
    end
  end

  def update
    task = Task.find(params[:id])
    task.name = params[:task_name]
    task.description = params[:task_description]
    task.category = params[:task_category]
    task.priority = params[:priority]
    task.added = Time.current
    task.user_add = current_user.name
    task.save!
    if params[:task_category] == params[:category]
      redirect_to tasks_path(category: params[:category])
    else
      redirect_to tasks_path
    end
  end

end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.delete(:user_id)
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!@current_user
  end
end

app/helpers/tasks_helper.rb
module TasksHelper
  def priority_color(priority)
    case priority
    when 1
      'text-success'
    when 2
      'text-warning'
    when 3
      'text-danger'
    else
      'text-primary'
    end
  end

  def priority_visualizer(priority)
    '!' * priority
  end
end

app/views/announcements/index.html.erb
<!-- Tab navbar -->
<div class="sticky-top">
  <!-- General Nav bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-dark p-0">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%= image_tag "bsfc_logo.png", {:alt => "Berkeley Student Food Collective Logo", :width => 40, :height => 40} %>
      </a>
      <small style="color: white;">Welcome <%= current_user.name %></small>
      <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class = "navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item text-end">
            <%= link_to "Log Out", logout_path, method: :post, class: "nav-link text-light" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Announcements nav bar -->
  <div>
    <!-- Switch between tabs -->
    <div class="dropdown w-100 px-1 border-bottom border-dark">
      <a class="btn dropdown-toggle fs-1 fw-bold" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
        Announcements
      </a>
        <ul class="dropdown-menu w-100 " style="box-shadow: 0 20px 20px grey" aria-labelledby="navigation-dropdown">
          <li>
            <%= link_to "Tasks", tasks_path, class: "dropdown-item fs-1 fw-bold" %>
          </li>
        </ul>
      </div>

      <!-- add announcement -->
      <div class="d-flex align-items-center justify-content-end px-3 py-2">
        <button type="button" class="btn btn-sm btn-danger">Post Announcement +</button>
      </div>
  </div>
</div>

<!-- Announcements div -->
<div id="announcements-div" class="container bg-light">
  <!-- Announcement panel -->
  <div class="announcement-panel row px-1 py-1 border-bottom border-top border-dark">
    <div class="col-11 ps-2 pt-2 pb-3">
      <div class="d-flex justify-content-between align-items-center">
        <h5 class="fw-bold m-0">This is an announcement!</h5>
      </div>
      <p class="fw-lighter small m-0" style="line-height: 2;"><small>Posted by Melody 9:00am 12/12/12</small></p>
      <p class="m-0" style="line-height: 1;">
        <small>
          Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
        </small>
      </p>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BerkeleyFoodCollective</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class = "container">
      <% flash.each do |message_type, message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    </div>
    <%= yield %>
    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  </body>
</html>

app/views/tasks/index.html.erb
<!-- Tab navbar -->
<div class="sticky-top bg-light">
  <!-- General Nav bar -->
  <nav class="navbar navbar-expand-lg navbar-light bg-dark p-0">
    <div class="container-fluid">
      <a class="navbar-brand" href="#">
        <%= link_to((image_tag "bsfc_logo.png", {:alt => "Berkeley Student Food Collective Logo", :width => 40, :height => 40}), announcements_path) %>
      </a>
      <small style="color: white;">Welcome <%= current_user.name %></small>
      <button class="navbar-toggler bg-light" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <li class="nav-item text-end">
            <%= link_to "Log Out", logout_path, method: :post, class: "nav-link text-light" %>
          </li>
        </ul>
      </div>
    </div>
  </nav>

  <!-- Tasks nav bar -->
  <div>
    <!-- Switch between tabs -->
    <div class="dropdown w-100 px-1 border-bottom border-dark">
      <a class="btn btn-light dropdown-toggle" href="#" role="button" id="dropdown-nav" data-bs-toggle="dropdown" aria-expanded="false">
        Tasks
      </a>
      <div class="dropdown-menu w-100" aria-labelledby="dropdown-nav">
        <%= link_to "Announcements", announcements_path, class: "dropdown-item" %>
      </div>
    </div>

    <!-- Select category and add task-->
    <div class="d-flex align-items-center justify-content-between px-3 py-1">
      <div id="filter-category-dropdown"class="d-flex align-items-center">
        <small class="me-1 my-2">Filter tasks by</small>
        <label>
          <select onchange="location=this.value;" id="category-filter" class="border-0 bg-light rounded text-secondary">
            <option value="<%= tasks_path %>" <%= params[:category].blank? ? 'selected' : ''%>>All Categories</option>
            <% @curr_categories.each do |category| %>
              <option value="<%= tasks_path(:category => category) %>" <%= params[:category] == category ? 'selected' : ''%>><%= category %></option>
            <% end %>
          </select>
        </label>
      </div>
      <button type="button" class="btn btn-sm btn-danger" data-bs-toggle="modal" data-bs-target="#add-task-modal">Add Task +</button>
    </div>
  </div>
</div>

<!-- Add Task Modal -->
<div class="modal fade" id="add-task-modal" tabindex="-1" aria-labelledby="add-task-modal" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Add New Task</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        <div class="d-flex justify-content-center">
          <%= image_tag "bsfc_logo.png", {:alt => "Berkeley Student Food Collective Logo", :width => 100, :height => 100} %>
        </div>
        <%= form_tag tasks_path(:category => params[:category]), :method => "post", :class => "" do %>
          <div class="mb-2">
            <%= label_tag :task_name, "Task Name", class: "form-label" %>
            <%= text_field_tag :task_name, nil, :placeholder => "New Task...", :class => "form-control" %>
          </div>
          <div class="mb-2">
            <%= label_tag :task_description, "Task Description", class: "form-label" %>
            <%= text_area_tag :task_description, nil, :placeholder => "Add new task description...", :class => "form-control" %>
          </div>
          <div class="mb-2">
            <%= label_tag :task_category, "Task Category", class: "form-label" %>
            <%= select_tag :task_category, options_for_select(@all_categories), :class => "form-control" %>
          </div>
          <div class="d-flex justify-content-center">
            <%= label_tag nil, "Task Priority", class: "form-label" %>
          </div>

          <div class="mb-3 d-flex justify-content-center">
            <div class="form-check form-check-inline">
              <%= radio_button_tag :priority, 1, true, class: "form-check-input" %>
              <%= label_tag :priority_low, 'Low', class: "form-check-label text-success" %>
            </div>
            <div class="form-check form-check-inline">
              <%= radio_button_tag :priority, 2, false, class: "form-check-input" %>
              <%= label_tag :priority_medium, 'Medium', class: "form-check-label text-warning" %>
            </div>
            <div class="form-check form-check-inline">
              <%= radio_button_tag :priority, 3, false, class: "form-check-input" %>
              <%= label_tag :priority_high, 'High', class: "form-check-label text-danger" %>
            </div>
          </div>
          <div class="mb-2 d-flex justify-content-center">
            <%= submit_tag "Add Task", :class => "btn btn-danger", :id => "submit-add-task" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="center">
  <h5>Incomplete Tasks</h5>
</div>
<% @tasks.each do |task| %>
  <% if @count == @num_incomplete && !@completed %>
    <% @count=0 %>
    <% @completed=true %>
    <div class="center">
      <h5>Completed Tasks</h5>
    </div>
  <% end %>
  <!-- Tasks div -->
  <div id="tasks-div" class="container">
    <!-- Task panel -->
    <div id='task-panel-<%= task.name %>' class="task-panel row px-1 py-1 border-bottom px-1<%= @count == 0 ? " border-top" : "" %> border-dark">
      <% @count += 1 %>
      <!-- Checkbox -->
      <div class="col-1 d-flex flex-column justify-content-center align-items-center">
        <% if task.completed %>
          <picture type='button' data-bs-toggle='modal' data-bs-target='#confirm-toggle-modal-<%= task.id %>'>
            <%= image_tag "checked_checkbox.png", {:alt => "Checked Checkbox", :width => 25, :height => 25} %>
          </picture>
        <% else %>
          <picture type='button' data-bs-toggle='modal' data-bs-target='#confirm-toggle-modal-<%= task.id %>'>
            <%= image_tag "empty_checkbox.png", {:alt => "Empty Checkbox", :width => 25, :height => 25} %>
          </picture>
        <% end %>
      </div>

      <!-- Right side of panel -->
      <div id='task-card-<%= task.name %>' class="col-10 ps-4 justify-content-between align-items-center">
        <div class="d-flex bd-highlight justify-content-center align-items-center">
          <h5 class='fw-bold bd-highlight <%= priority_color task.priority %>'>
            <%= priority_visualizer task.priority  %> &nbsp
          </h5>
          <h5 class="fw-bold ml-0 bd-highlight">
            <%=   task.name   %>
          </h5>
          <span class="badge bg-dark ms-auto bd-highlight" >
            <%= task.category %>
          </span>
        </div>
        <% if task.completed %>
          <p class="fw-lighter small m-0">
            <small class="complete">
              Completed by <%=  task.user_complete  %> at <%= task.complete_time.strftime('%I:%M %p %Z') %> on <%= task.complete_time.strftime('%b %d %Y') %>
            </small></p>
        <% end %>
        <p class="fw-lighter small m-0">
          <small>
            Posted by <%= task.user_add %> at <%= task.added.strftime('%I:%M %p %Z') %> on <%= task.added.strftime('%b %d %Y') %>
         </small></p>
        <p class="m-0">
          <small>
            <%= task.description %>
          </small>
        </p>
      </div>
      <div class="col-1 d-flex flex-column justify-content-center align-items-center">
        <div class='triple-dot-menu' type="button" data-bs-toggle='modal' data-bs-target='#edit-task-modal-<%= task.id %>'></div>
      </div>
    </div>
  </div>

  <!-- Confirm Complete Task Modal -->
  <div class="modal fade" id="confirm-toggle-modal-<%= task.id %>" tabindex="-1" aria-labelledby="confirm-toggle-modal-<%= task.id %>" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <% if task.completed %>
            <h5 class="modal-title">Confirm Task Undo</h5>
          <% else %>
            <h5 class="modal-title">Confirm Task Completion</h5>
          <% end %>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex justify-content-center">
            <%= image_tag "bsfc_logo.png", {:alt => "Berkeley Student Food Collective Logo", :width => 100, :height => 100} %>
          </div>
          <h5 class="d-flex justify-content-center">
            <%= task.name %>
          </h5>
          <div class="d-flex justify-content-center">
            <%= task.description %>
          </div>
          <div>&nbsp</div>
          <% if task.completed %>
            <div class="mb-2 d-flex justify-content-center">
              <%= button_to "Undo Task Completion", checkmark_path(:id => task, :user => current_user, :category => params[:category], :check_type => "unchecking"), :class => "btn btn-danger" %>
            </div>
          <% else %>
            <div class="mb-2 d-flex justify-content-center">
              <%= button_to "Complete Task", checkmark_path(:id => task, :user => current_user, :category => params[:category], :check_type => "checking"), :class => "btn btn-success" %>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  
  <!-- Edit Task Modal -->
  <div class="modal fade" id="edit-task-modal-<%= task.id %>" tabindex="-1" aria-labelledby="edit-task-modal-<%= task.id %>" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title">Edit Existing Task</h5>
          <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <div class="d-flex justify-content-center">
            <%= image_tag "bsfc_logo.png", {:alt => "Berkeley Student Food Collective Logo", :width => 100, :height => 100} %>
          </div>
          <%= form_tag task_path(:id => task, :category => params[:category]), :method => "put", :class => "" do %>
            <div class="mb-2">
              <%= label_tag :task_name, "Task Name", class: "form-label" %>
              <%= text_field_tag :task_name, nil, :placeholder => "New Task...", :class => "form-control", :value => task.name %>
            </div>
            <div class="mb-2">
              <%= label_tag :task_description, "Task Description", class: "form-label" %>
              <%= text_area_tag :task_description, task.description, :placeholder => "Add new task description...", :class => "form-control" %>
            </div>
            <div class="mb-2">
              <%= label_tag :task_category, "Task Category", class: "form-label" %>
              <%= select_tag :task_category, options_for_select(@all_categories, task.category), :class => "form-control" %>
            </div>
            <div class="d-flex justify-content-center">
              <%= label_tag nil, "Task Priority", class: "form-label" %>
            </div>
            <div class="mb-3 d-flex justify-content-center">
              <div class="form-check form-check-inline">
                <%= radio_button_tag :priority, 1, task.priority == 1, class: "form-check-input" %>
                <%= label_tag :priority_low, 'Low', class: "form-check-label text-success" %>
              </div>
              <div class="form-check form-check-inline">
                <%= radio_button_tag :priority, 2, task.priority == 2, class: "form-check-input" %>
                <%= label_tag :priority_medium, 'Medium', class: "form-check-label text-warning" %>
              </div>
              <div class="form-check form-check-inline">
                <%= radio_button_tag :priority, 3, task.priority == 3, class: "form-check-input" %>
                <%= label_tag :priority_high, 'High', class: "form-check-label text-danger" %>
              </div>
            </div>
            <div class="mb-2 d-flex justify-content-center">
              <%= submit_tag "Edit Task", :class => "btn btn-danger" %>
            </div>
          <% end %>
          <div class="mb-2 d-flex justify-content-center">
            <%= button_to "Delete Task", task_path(id: task, category: params[:category]), :method => "delete", :class => "btn btn-danger" %>
          </div>
        </div>
      </div>
    </div>
  </div>

<% end %>